### ISSUE TITLE
how can i do inference?

### ISSUE THREAD

**Issue by vivasvan1** [abdo-eldesokey/RAFT-NCUP#1]
I have some images I want to generate the output for this algo.

**Comment by SikanderBinMukaram** [comment]
use demo.py. use this command as used by https://github.com/princeton-vl/RAFT . put your images in demo-frames and download the pretrained models into model folder.

**Comment by Highlightbeast** [comment]
> use demo.py. use this command as used by https://github.com/princeton-vl/RAFT . put your images in demo-frames and download the pretrained models into model folder.

Hey, thank you for your reply. And I tried the method you mentioned above however there occurs a problem that the demo could not run with the given RAFT+NCUP model. If you succeed in realizing inference, plz let me know how you have done that. Thank you sooo much.

**Comment by Highlightbeast** [comment]
Problem solved thank you :)
