### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for DataParallel:

### ISSUE THREAD

**Issue by Highlightbeast** [abdo-eldesokey/RAFT-NCUP#3]
Thank you for your excellent works on optical flow. When I was doing the inference with some images from my own, there occurs a RuntimeError. 
I have download all the models you provided on GitHub can be categorized into two parts.
The model from standard RAFT provided by Zachary Teed and Jia Deng. All these four models work fine in demo.py. https://drive.google.com/drive/folders/1sWDsfuZ3Up38EUQt7-JDTT1HcGHuJgvT
raft-sintel.pth
raft-kitti.pth
raft-things.pth
raft-chairs.pth
However, the if I change the model with "raft_nc-sintel.pth", "raft_nc_kitti.pth" or "raft_nc-thing.pth", the following RuntimeError just arise. 
I think these pre-trained models with "nc" are the RAFT_NCUP estimator, right? And has the demo.py also been refined to execrate the inference for the new model trained with nc upsampler other than the standard one?

    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.update_block.mask.0.weight", "module.update_block.mask.0.bias", "module.update_block.mask.2.weight", "module.update_block.mask.2.bias". 
	Unexpected key(s) in state_dict: "module.upsampler.interpolation_net.nconv_in.weight_p", "module.upsampler.interpolation_net.nconv_x2.0.weight_p", "module.upsampler.interpolation_net.encoder.0.0.weight_p", "module.upsampler.interpolation_net.encoder.0.1.0.weight_p", "module.upsampler.interpolation_net.encoder.1.weight_p", "module.upsampler.interpolation_net.decoder.0.weight_p", "module.upsampler.interpolation_net.nconv_out.weight_p", "module.upsampler.weights_est_net.conv.0.0.weight", "module.upsampler.weights_est_net.conv.0.0.bias", "module.upsampler.weights_est_net.conv.0.1.weight", "module.upsampler.weights_est_net.conv.0.1.bias", "module.upsampler.weights_est_net.conv.0.1.running_mean", "module.upsampler.weights_est_net.conv.0.1.running_var", "module.upsampler.weights_est_net.conv.0.1.num_batches_tracked", "module.upsampler.weights_est_net.conv.1.0.weight", "module.upsampler.weights_est_net.conv.1.0.bias", "module.upsampler.weights_est_net.conv.1.1.weight", "module.upsampler.weights_est_net.conv.1.1.bias", "module.upsampler.weights_est_net.conv.1.1.running_mean", "module.upsampler.weights_est_net.conv.1.1.running_var", "module.upsampler.weights_est_net.conv.1.1.num_batches_tracked", "module.upsampler.weights_est_net.out.weight", "module.upsampler.weights_est_net.out.bias"

**Comment by Highlightbeast** [comment]
Problem solved. And the reason is that the model with the new upsampler needs way more parameters than the standard one. Or we could say they are totally different networks in the aspect of parameters. 

The inference part works fine after the modification of the demo.py which incorporates a bash file describing parameters in the new model. 
1.  Add the parameters needed during evaluation(check the parameters in "evulate.py").
2. Give all the parameter values in a new bash file like "eval_raft_nc_kitti.sh" file(pay attention to the key "--dataset", we just need to give the path of the images we want to put in, rather than the dataset like "sintel" or "kitti").
3.  And of course, since the upsampler has already changed, we need to change something in raft_nc_dbl.py class RAFT. 
Just add
        if args.final_upsampling is not None:
            self.update_block.mask = nn.Sequential()
to avoid the relative parameters using in convex combination upsampler in standard RAFT.

**Comment by Androsimus** [comment]
@Highlightbeast Hi!
I did all you mentioned, but I still get the same as in your first post here.
Could you clarify, where exactly did you add this
```
if args.final_upsampling is not None:
   self.update_block.mask = nn.Sequential()
```
Because I added it to raft_nc_dbl.py class RAFT in `__init__` function, so I substituted string `self.update_block.mask = nn.Sequential()`

Or maybe there were some other patches?
